import React from 'react';
import jsPDF from 'jspdf';

function PDFReport({ scanData, type }) {
  const generatePDF = () => {
    if (!scanData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('PhantomBreaker', pageWidth / 2, y, { align: 'center' });
    y += 8;

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(type || 'Scan Report', pageWidth / 2, y, { align: 'center' });
    y += 6;

    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(new Date().toLocaleString(), pageWidth / 2, y, { align: 'center' });
    doc.setTextColor(0);
    y += 12;

    doc.setLineWidth(0.5);
    doc.line(15, y, pageWidth - 15, y);
    y += 10;

    // Threat score (works for phishing/deepfake style results)
    if (scanData.combined_threat_score !== undefined || scanData.threat_score !== undefined) {
      const score = scanData.combined_threat_score ?? scanData.threat_score;
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text(`Threat Score: ${score}/100`, 15, y);
      y += 8;
    }

    if (scanData.is_phishing !== undefined) {
      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      doc.text(`Result: ${scanData.is_phishing ? 'Phishing Detected' : 'Safe'}`, 15, y);
      y += 8;
    }

    if (scanData.language_detected) {
      doc.text(`Language: ${scanData.language_detected}`, 15, y);
      y += 8;
    }

    // Explanation
    if (scanData.explanation) {
      y += 4;
      doc.setFont(undefined, 'bold');
      doc.text('Explanation:', 15, y);
      y += 6;
      doc.setFont(undefined, 'normal');
      const lines = doc.splitTextToSize(scanData.explanation, pageWidth - 30);
      doc.text(lines, 15, y);
      y += lines.length * 6 + 4;
    }

    // Dangerous sentences
    if (scanData.dangerous_sentences?.length > 0) {
      doc.setFont(undefined, 'bold');
      doc.text('Dangerous Sentences:', 15, y);
      y += 6;
      doc.setFont(undefined, 'normal');
      scanData.dangerous_sentences.forEach(sentence => {
        const lines = doc.splitTextToSize(`- ${sentence}`, pageWidth - 30);
        if (y + lines.length * 6 > 280) { doc.addPage(); y = 20; }
        doc.text(lines, 15, y);
        y += lines.length * 6 + 2;
      });
      y += 4;
    }

    // Manipulation tactics
    if (scanData.manipulation_tactics?.length > 0) {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.setFont(undefined, 'bold');
      doc.text('Manipulation Tactics:', 15, y);
      y += 6;
      doc.setFont(undefined, 'normal');
      doc.text(scanData.manipulation_tactics.join(', '), 15, y);
      y += 10;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by PhantomBreaker Security Platform', pageWidth / 2, 290, { align: 'center' });

    doc.save(`phantombreaker-${(type || 'report').toLowerCase().replace(/\s+/g, '-')}.pdf`);
  };

  return (
    <button
      className="btn-primary"
      onClick={generatePDF}
      style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
    >
      📄 Download PDF Report
    </button>
  );
}

export default PDFReport;